In [1]:
import numpy as np

In [2]:
df = np.array(43)

print(df.ndim)

0


In [3]:
df = np.array([43,45])
print(df.ndim)

1


In [4]:
df  = np.array([[1,2,3],[1,4,5],[7,8,9]])
print(df.ndim)

2


The total opening [ brackets before any value appears is the total dimension of the array

In [5]:
df = np.array([[[[45],[46],[47]]]])
print(df.ndim)

4


ndmin is used to change the dimension of an array

In [6]:
x = [[32,2,45], [54,3,23]]
y = np.array(x, ndmin=15)

print(y)

y.ndim

[[[[[[[[[[[[[[[32  2 45]
              [54  3 23]]]]]]]]]]]]]]]


15

In [7]:
x  = np.array(['hello ', 26, 'world'])

print(x[0] + x[1])

hello 26


In [8]:
x = [[23,44,2],[34,12,76]]

y =np.array(x)

print(y[1,2])

76


In [9]:
y =np.array([[[[23,34,2],[34,12,76],[78,45,65],[90,43,87]]]])

print(y[0,0,3, 2])

87


In [10]:
y =np.array([[[[[[[[[23,34,2]]],[[[34,12,76]]],[[[78,45,65]]],[[[90,43,87]]]]]]]]])

print(y[0,0,0,0,0,3,0,0,2])

print(y.ndim)


87
9


In [11]:
x = ("hello world")

df  = len(x)

print(x[0:4], x[6:df])


hell world


In [12]:
df  = np.array([23,34,12,24,45])

print(df[3:4])

[24]


In [13]:
df  = np.array([23,34,12,24,45,78,44])

print(df[1:4:1]) #Start Stop Step

[34 12 24]


In [14]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


In [15]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

# df[2,1:4]

print(df[2,1:4])

[11 12 13]


In [16]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

print(df[2,::3])

[10 13]


In [17]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

print(df[1::1])

[[ 1  2  3  4  5]
 [10 11 12 13 14]]


In [18]:
df = np.array([[23,34,12,24,45],
               [1,2,3,4,5],
               [7,23,45,23,47]])

print(df[0:2,0:2]) #array slicing method

[[23 34]
 [ 1  2]]


In [19]:
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

arr[0] = 42

print(arr)
print(x)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


In [20]:
x = np.array([[[1,2,3,4,5]]])

for i in x:
    for j in i:
        for k in j:
            print(k)


1
2
3
4
5


In [21]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

print(df.shape)

(3, 5)


In [22]:
df = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr=df.reshape(4,3)

newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
df = np.array([1,2,3,4,5,6,7,8,9,10,11,12])


newarr=df.reshape(3, 2, 2)

print(newarr.reshape(-1))

newarr

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
arr = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

for i in np.nditer(arr):
    print(i)

23
34
12
24
45
1
2
3
4
5
10
11
12
13
14


In [32]:
a = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])
# it = np.nditer(a, flags=['external_loop','buffered'],op_dtypes=['float'])

it = np.nditer(a, flags=['zerosize_ok','buffered'],op_dtypes=['float'])

for x in it:
    # print(f"Value: {x}, Index: {it.multi_index}")
    print(x)

for y in np.nditer(a, flags=['buffered'], op_dtypes=['complex128']):
    print(y)

for m in np.nditer(a, flags=['buffered'], op_dtypes=['S']):
    print(m)

23.0
34.0
12.0
24.0
45.0
1.0
2.0
3.0
4.0
5.0
10.0
11.0
12.0
13.0
14.0
(23+0j)
(34+0j)
(12+0j)
(24+0j)
(45+0j)
(1+0j)
(2+0j)
(3+0j)
(4+0j)
(5+0j)
(10+0j)
(11+0j)
(12+0j)
(13+0j)
(14+0j)
np.bytes_(b'23')
np.bytes_(b'34')
np.bytes_(b'12')
np.bytes_(b'24')
np.bytes_(b'45')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')
np.bytes_(b'13')
np.bytes_(b'14')


In [48]:
arr1=[23,34,12,24,45]
arr2=[1,2,3,4,5]
arr3=[10,11,12,13,14]


x = np.concatenate((arr1,arr2,arr3))

print(x)

a1=[arr1[2]]
a2=[arr2[1]]
a3=[arr3[3]]

# a4=[a1]
# a5=[a2]
# a6=[a3]


y = np.concatenate([a1,a2,a3])

print(y)

[23 34 12 24 45  1  2  3  4  5 10 11 12 13 14]
[12  2 13]


In [50]:
arr1=np.array([[23,34],[12,24]])
arr2=np.array([[1,2], [3,4]])
arr3=np.array([[10,11], [12,13]])

x  = np.concatenate((arr1,arr2,arr3))

print(x)

[[23 34]
 [12 24]
 [ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]


In [52]:
arr1=np.array([[23,34],[12,24]])
arr2=np.array([[1,2], [3,4]])
arr3=np.array([[10,11], [12,13]])

x  = np.concatenate((arr1,arr2,arr3),axis=1)

print(x)

[[23 34  1  2 10 11]
 [12 24  3  4 12 13]]


In [54]:
arr1=np.array([[23,34],[12,24]])
arr2=np.array([[1,2], [3,4]])
arr3=np.array([[10,11], [12,13]])

x  = np.stack((arr1,arr2,arr3),axis=1)

print(x)

[[[23 34]
  [ 1  2]
  [10 11]]

 [[12 24]
  [ 3  4]
  [12 13]]]


In [56]:
arr1=np.array([[23,34],[12,24]])
arr2=np.array([[1,2], [3,4]])
arr3=np.array([[10,11], [12,13]])

x  = np.hstack((arr1,arr2,arr3))#Same as axis=0

print(x)

[[23 34  1  2 10 11]
 [12 24  3  4 12 13]]


In [58]:
arr1=np.array([[23,34],[12,24]])
arr2=np.array([[1,2], [3,4]])
arr3=np.array([[10,11], [12,13]])

x  = np.vstack((arr1,arr2,arr3))#Same as axis=1

print(x)

[[23 34]
 [12 24]
 [ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]


In [60]:
arr1=np.array([[23,34],[12,24]])
arr2=np.array([[1,2], [3,4]])
arr3=np.array([[10,11], [12,13]])

x  = np.dstack((arr1,arr2,arr3))

print(x)

[[[23  1 10]
  [34  2 11]]

 [[12  3 12]
  [24  4 13]]]


In [66]:
arr = np.array([1,2,3,4,5,6,7,8,9])

x  = np.array_split(arr,4)

print(x)

for i in x:
    print(i)


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[1 2 3]
[4 5]
[6 7]
[8 9]


In [73]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

x  = np.array_split(arr,3)

print(x)

for i in x:
    print(i)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [75]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

x  = np.array_split(arr,3,axis=1)

print(x)

for i in x:
    print(i)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]
