In [4]:
import numpy as np

In [5]:
df = np.array(43)

print(df.ndim)

0


In [6]:
df = np.array([43,45])
print(df.ndim)

1


In [7]:
df  = np.array([[1,2,3],[1,4,5],[7,8,9]])
print(df.ndim)

2


The total opening [ brackets before any value appears is the total dimension of the array

In [8]:
df = np.array([[[[45],[46],[47]]]])
print(df.ndim)

4


ndmin is used to change the dimension of an array

In [9]:
x = [[32,2,45], [54,3,23]]
y = np.array(x, ndmin=15)

print(y)

y.ndim

[[[[[[[[[[[[[[[32  2 45]
              [54  3 23]]]]]]]]]]]]]]]


15

In [10]:
x  = np.array(['hello ', 26, 'world'])

print(x[0] + x[1])

hello 26


In [11]:
x = [[23,44,2],[34,12,76]]

y =np.array(x)

print(y[1,2])

76


In [12]:
y =np.array([[[[23,34,2],[34,12,76],[78,45,65],[90,43,87]]]])

print(y[0,0,3, 2])

87


In [13]:
y =np.array([[[[[[[[[23,34,2]]],[[[34,12,76]]],[[[78,45,65]]],[[[90,43,87]]]]]]]]])

print(y[0,0,0,0,0,3,0,0,2])

print(y.ndim)


87
9


In [14]:
x = ("hello world")

df  = len(x)

print(x[0:4], x[6:df])


hell world


In [15]:
df  = np.array([23,34,12,24,45])

print(df[3:4])

[24]


In [16]:
df  = np.array([23,34,12,24,45,78,44])

print(df[1:4:1]) #Start Stop Step

[34 12 24]


In [17]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


In [23]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

# df[2,1:4]

print(df[2,1:4])

[11 12 13]


In [25]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

print(df[2,::3])

[10 13]


In [28]:
df = np.array([[23,34,12,24,45],[1,2,3,4,5],[10,11,12,13,14]])

print(df[1::1])

[[ 1  2  3  4  5]
 [10 11 12 13 14]]


In [ ]:
df = np.array([[23,34,12,24,45],
               [1,2,3,4,5],
               [7,23,45,23,47]])

print(df[0:2,0:2]) #array slicing method

[[23 34]
 [ 1  2]]
