In [2]:
import numpy as np

In [4]:
df = np.array(43)

print(df.ndim)

0


In [7]:
df = np.array([43,45])
print(df.ndim)

1


In [12]:
df  = np.array([[1,2,3],[1,4,5],[7,8,9]])
print(df.ndim)

2


The total opening [ brackets before any value appears is the total dimension of the array

In [14]:
df = np.array([[[[45],[46],[47]]]])
print(df.ndim)

4


ndmin is used to change the dimension of an array

In [16]:
x = [[32,2,45], [54,3,23]]
y = np.array(x, ndmin=15)

print(y)

y.ndim

[[[[[[[[[[[[[[[32  2 45]
              [54  3 23]]]]]]]]]]]]]]]


15

In [19]:
x  = np.array(['hello ', 26, 'world'])

print(x[0] + x[1])

hello 26


In [22]:
x = [[23,44,2],[34,12,76]]

y =np.array(x)

print(y[1,2])

76


In [33]:
y =np.array([[[[23,34,2],[34,12,76],[78,45,65],[90,43,87]]]])

print(y[0,0,3, 2])

87


In [70]:
y =np.array([[[[[[[[[23,34,2]]],[[[34,12,76]]],[[[78,45,65]]],[[[90,43,87]]]]]]]]])

print(y[0,0,0,0,0,3,0,0,2])

print(y.ndim)


87
9


In [78]:
x = ("hello world")

df  = len(x)

print(x[0:4], x[6:df])


hell world


In [79]:
df  = np.array([23,34,12,24,45])

print(df[3:4])

[24]


In [ ]:
df  = np.array([23,34,12,24,45,78,44])

print(df[1:4:1]) #Start Stop Step

[34 12 24]


In [82]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9
